---
- name: Tomcat deployment playbook
  hosts: tomcat_nodes       # Inventory hosts group / server to act on
  become: yes               # If to escalate privilege
#  become_method: sudo       # Set become method
#  remote_user: root         # Update username for remote server
  vars:
    tomcat_ver: 10.1.41                          # Tomcat version to install
    ui_manager_username: manager                    # User who can access the UI manager section only
    ui_manager_pass: manager                    # UI manager user password
    ui_admin_username: admin                    # User who can access bpth manager and admin UI sections
    ui_admin_pass: admin                        # UI admin password
    deployer_username: deployer
    deployer_pass: deployer
  roles:
    - tomcat

