- name: Install Java 11 CentOS
  yum:
    name: java-11-openjdk-headless
    state: present

- name: Add tomcat group
  group:
    name: tomcat

- name: Add "tomcat" user
  user:
    name: tomcat
    group: tomcat
    home: "{{ tomcat_install_path }}"
    createhome: yes
    system: yes

- name: Download Tomcat
  get_url:
    url: "{{ tomcat_archive_url }}"
    dest: "{{ tomcat_archive_dest }}"

- name: Create a tomcat directory
  file:
    path: "{{ tomcat_install_path }}"
    state: directory
    owner: tomcat
    group: tomcat

- name: Extract tomcat archive
  unarchive:
    src: "{{ tomcat_archive_dest }}"
    dest: "{{ tomcat_install_path }}"
    owner: tomcat
    group: tomcat
    remote_src: yes
    extra_opts: "--strip-components=1"
    creates: "{{ tomcat_install_path }}/bin"

- name: Copy tomcat service file
  template:
    src: templates/tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service
  when: ansible_service_mgr == "systemd"

- name: Start and enable firewalld
  service:
    name: firewalld
    state: started
    enabled: yes
  when: ansible_service_mgr == "systemd"

- name: Open tomcat port on the firewall
  firewalld:
    port: 8080/tcp
    permanent: true
    state: enabled
    immediate: yes
  when: ansible_service_mgr == "systemd"

- name: Start and enable tomcat
  service:
    daemon_reload: yes
    name: tomcat
    state: started
    enabled: yes
  when: ansible_service_mgr == "systemd"

- name: Set UI access credentials
  template:
    src: tomcat-users.xml.j2
    dest: "{{ tomcat_install_path }}/conf/tomcat-users.xml"
#  notify: restart tomcat

- name: Allow access to Manager and Host Manager apps from any IP
  template:
    src: context.xml.j2 
    dest: "{{ item }}"
  with_items:
    - "{{ tomcat_install_path }}/webapps/host-manager/META-INF/context.xml"
    - "{{ tomcat_install_path }}/webapps/manager/META-INF/context.xml"
  notify: restart tomcat
  
- name: Download a WAR File to the Tomcat webapps directory to be deployed
  community.general.maven_artifact:
    group_id: org.uax.devops
    artifact_id: demo-web-project
    extension: war
    repository_url: 'http://10.0.0.8:8081'
    username: jenkins
    password: 3085Joguch@Jen
    version: 1.11
    dest: "{{ tomcat_install_path }}/webapps/demo-web-project.war"
